FilmRate 1.0
Cakypa217/filmorate1 pull request #1
Opened 2024-09-29 05:17 UTC by Cakypa217

2024-09-29 20:54 UTC, YazykovMikhail requested changes

2024-09-29 20:54 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, 12, 28);
Статические переменные обьявляются первыми в классе по кодстайлу

2024-09-29 20:54 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
Стандартный шаблон для логов
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-09-29 20:54 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private long getNextId() {
представь что у тебя 976890098 фильмов, и что бы создать новый ты должен пробеаться по всем что ьы вычислить максимальное занчение идентификатора и так каждый раз. 
Лучше сделай как было в TaskManager поле которое будет счетчиком

2024-09-29 20:54 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
Советую посмотреть на аннотации для валидации
@NotBlank

А в методах котролерах ставишь @Valid на входящий параметр-тело

2024-09-30 19:44 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate CINEMA_BIRTHDAY = LocalDate.of(1895, 12, 28);
исправил

2024-09-30 19:48 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private long getNextId() {
исправил

2024-09-30 19:59 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@Slf4j
исправил

2024-09-30 20:26 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private String name;
Исправил

2024-09-30 20:28 UTC, Cakypa217 commented
Все недочеты исправил

2024-10-01 14:58 UTC, YazykovMikhail approved these changes

2024-10-01 14:58 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Добавлен фильм с идентификатором {}", newFilm.getId());
Этот лог уже лшний

2024-10-01 14:58 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.info("Фильм с идентификатором {} обновлен.", newFilm.getId());
Этот лог уже лишний

2024-10-10 01:29 UTC, merged