Develop
Cakypa217/filmorate1 pull request #19
Opened 2024-11-29 11:34 UTC by Cakypa217

2024-11-30 22:43 UTC, YazykovMikhail requested changes

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +
Нет логирования

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
нет логирвоания ответа

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +@Slf4j
нет логирования ответа в методах контроллера

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Отправлен ответ GET /users/{}/recommendations с количеством фильмов: {}", id, recommendedFilms.size());
честно говоря стоит логировать сам список, а не его размер.
Размер может быть одтнаковый, но элементы разные, смысл логирование - разобраться в будущем с проблемами

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dto/DirectorDto.java
> +    @NotNull
@NotNull
    @NotBlank
Посмотрите разницу между ними и оставьте что-то одно

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          log.info("Отправлен ответ с FilmMapper.mapToFilmDto(film): {}", FilmMapper.mapToFilmDto(film));
сначала делается конвертация для лога, а потом что бы вернуть овтет - одно и тоже действие повторяется дважды.
Сначала сделать конвертацию, потом залогировать сконвертирвоанный обьект и потом его же вернуть

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          log.info("Отправлен ответ с FilmMapper.mapToFilmDto(film): {}", FilmMapper.mapToFilmDto(film));
Поправьте везде

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    public List<Film> getPopularFilms(Integer count, Optional<Long> genreId, Optional<Integer> year) {
Репозиторий не должен принимать Optional, он принимает готовые данные, если данные не готовы или их нет, не стоит их передавать в слой для работы с хранилищем

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    public List<Film> getPopularFilms(Integer count, Optional<Long> genreId, Optional<Integer> year) {
Поправьте везде

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Отправлен ответ GET /users/{}/recommendations с количеством фильмов: {}", id, recommendedFilms.size());
Поправьте везде

2024-11-30 22:43 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    ReviewService reviewService;
private final

2024-12-01 11:19 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    ReviewService reviewService;
Исправили.

2024-12-01 11:19 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +    public List<Film> getPopularFilms(Integer count, Optional<Long> genreId, Optional<Integer> year) {
Исправили.

2024-12-01 11:19 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>          log.info("Отправлен ответ с FilmMapper.mapToFilmDto(film): {}", FilmMapper.mapToFilmDto(film));
Исправили.

2024-12-01 11:19 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dto/DirectorDto.java
> +    @NotNull
Исправили.

2024-12-01 11:20 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        log.info("Отправлен ответ GET /users/{}/recommendations с количеством фильмов: {}", id, recommendedFilms.size());
Исправили.

2024-12-01 11:20 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +@Slf4j
Исправили.

2024-12-01 11:20 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    }
Исправили.

2024-12-01 11:20 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +
Исправили.

2024-12-01 19:28 UTC, YazykovMikhail approved these changes

2024-12-04 22:51 UTC, merged