FilmRate 2.0
Cakypa217/filmorate1 pull request #2
Opened 2024-10-13 05:33 UTC by Cakypa217

FilmoRate 2.0

2024-10-14 16:11 UTC, YazykovMikhail reviewed
This branch has conflicts that must be resolved - у тебя конфиликт, подтянуть актуальный мастер в ветку и сделать новый ПР

2024-10-14 16:20 UTC, YazykovMikhail requested changes

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
Напомню про логироваени:

Стандартный шаблон для логов
```
createMethod(Request request) {
log.info("пришел Post запрос /films с телом: {}", request)
Response response = //логика метода, если есть бизнес процессы для логирвоания логируем их
log.info("Отправлен ответ Post /films с телом: {}", response)
}
```
что бы было видно что пришло, что ушло и если были какие то изменения в процессы выполнянения тоже были видны, потому что ты пойдешь в логи когда у тебя что то сломалось, просто по сообщения "Фильм добалвен" ничего не понятно.

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.validateFilm(film);
Не нужно тут вызывать валиадцию, если валидация в сервисе, путь там и вызывается

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) {
Стоит таки использовать @Valid и соответствующие аннотации

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (userService.getUserById(userId) == null) {
проверяй это в сервисе

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        film.setId(generatorId++);
++generatorId

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private long generatorId = 1;
и тогда счетчик начинай с 0
  private long generatorId = 0;
  
Каждый метод долен генерировать для себя идентификатор

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
Стоит добавить @JsonIgnore
что бы не менять данные эндпоинтами коттрые отвечабт за Фильм, ведь для управления лайками есть свои эндпоинты, а тут они просто хранятся

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
Стоит добавить @JsonIgnore
что бы не менять данные в эндпоинтах которые отвечают за Пользователей, ведь для управления лайками есть свои эндпоинты, а тут они просто хранятся

2024-10-14 16:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.validateUser(user);
раз методы для проверки валидации и сервисе, вызывай их в сервисе

2024-10-15 01:17 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  @Slf4j
исправил

2024-10-15 01:19 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        filmService.validateFilm(film);
исправил

2024-10-15 01:25 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (userService.getUserById(userId) == null) {
исправил

2024-10-15 01:26 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        userService.validateUser(user);
исправил

2024-10-15 01:58 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@RequestBody Film film) {
исправил

2024-10-15 01:59 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        film.setId(generatorId++);
исправил

2024-10-15 01:59 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private long generatorId = 1;
исправил

2024-10-15 02:13 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likes = new HashSet<>();
исправил

2024-10-15 02:13 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friends = new HashSet<>();
исправил

2024-10-15 06:45 UTC, closed without merging