Add database
Cakypa217/filmorate1 pull request #5
Opened 2024-11-13 16:13 UTC by Cakypa217

2024-11-14 21:28 UTC, YazykovMikhail requested changes

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Найдены фильмы: {}", filmRepository.findAll());
Представояешь ты ради лога идешь в бд дял получения всех фильмов
А потом еще отдельны выполняешь точно такой же запрос для возврата. 
Между ними и данные могут поменяться и в целом делать запрос для лога это не очень. 
Нужно логировать то что будет возвращено

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Получен запрос на получение всех фильмов");
Не информативный лог, до этого уже будет залогировано в контроллере, а к этому логу ничего не поменяется, это лишнее

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/resources/data.sql
> +
Вообще все запросы что нидже этого комментария лучше удалить. В реальном приложении их ни в коем случае делать нельзя. 
Все данные должны заполняться пользователм, кроме статичных. 
А сейчас у тебя конфигурируются тестовые данные в реальном приложении

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +);
mpa_id      int references MPA(mpa_id),

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +);
Это связь один ко многим

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_mpa (
Эта таблица не нужно, эта связь один ко многим

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        return jdbc.query(FIND_ALL_FILMS, mapper);
А как же поля mpa и genre ты их тут не возвращаешь

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        return jdbc.query(FIND_ALL_FILMS, mapper);
Вот такой запрос стот вызывать
select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID
а как получить жанры покажу в сервисе

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Найдены фильмы: {}", filmRepository.findAll());
public List<Film> getAll() {
		final List<Film> films = filmRepository.getAll();
		genreRepository.load(films);
		return films;
	}

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Найдены фильмы: {}", filmRepository.findAll());
Что бы заполнить для всех фильмов жанры, первым прходить на ум прогнать все запросы в цикле, но запросы в цикле прогонять не стоит. При каждом запросе создается подклчючение к БД - это тяжеловестная операция. 

поэтому можно загрузить таким образом:
```
	@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(Film::getId).toArray());
	}
```
где makeGenre выглядит так
```
	static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}
```

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Genre> genres = genreRepository.getGenresForFilm(filmId);
Жанры получаются тут так же как и для всех фильмов, метод у тебя уже есть, но там на вход принимается список, можно схитить:
		genreStorage.load(Collections.singletonList(film));

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Long mpaId = mpaRepository.getMpaForFilm(filmId);
Как ты уже понял МПА это один ко меногим, так что это можно получить их в запросе, по примеру запроса на получения всех фильмов

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmDto updateFilm(NewFilmRequest newFilmRequest) {
Сложновато, вот так будет попроще:
```
	public Film update(NewFilmRequest newFilmRequest) {
		final Film film = storage.get(newFilmRequest.getId());
		newFilmRequest.setRate(film.getRate());
		storage.update(newFilmRequest);
		return FilmMapper.mapToFilmDto(newFilmRequest);
	}
```

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmDto updateFilm(NewFilmRequest newFilmRequest) {
А метод обновления будет вот таким:
```
	@Override
	public void update(Film film) {
		String sqlQuery = "update FILMS SET NAME = ?, DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, RATE = ?, MPA_ID = ? " + " WHERE FILM_ID = ?";
		jdbcTemplate.update(sqlQuery, film.getName(), film.getDescription(), film.getReleaseDate(), film.getDuration(), film.getRate(), film.getMpa().getId(), film.getId());
		saveGenres(film);
	}
```
```
	private void saveGenres(Film film) {
		final Long filmId = film.getId();
		jdbcTemplate.update("delete from FILM_GENRES where FILM_ID = ?", filmId);
		final Set<Genre> genres = film.getGenres();
		if (genres == null || genres.isEmpty()) {
			return;
		}
		final ArrayList<Genre> genreList = new ArrayList<>(genres);
		jdbcTemplate.batchUpdate(
				"insert into FILM_GENRES (FILM_ID, GENRE_ID) values (?, ?)",
				new BatchPreparedStatementSetter() {
					public void setValues(PreparedStatement ps, int i) throws SQLException {
						ps.setLong(1, filmId);
						ps.setLong(2, genreList.get(i).getId());
					}

					public int getBatchSize() {
						return genreList.size();
					}
				});
	}
```

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Название фильма не может быть пустым")
В модели не нужны методы для валидации, валидация просходит на уровне контроллера, на уровне контроллера приходят дто, как рах в них и убдет валиадция.

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/resources/schema.sql
> +);
Я бы рекомендовал ввести еще поле
    rate        int,
что бы было болле удобно подсчитывать рейтинг фильма

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +
Вынеси лайки в отдельную класс. Каждая репозитория работает со совими таблицами/данными. 
И если добавишь поле рейтинг, то при удалении/добавлении нужно убдет вызыать вот такой метод:
```
	private void updateRate(long filmId) {
		String sqlQuery = "update FILMS f set rate = (select count(l.user_id) from LIKES l where l.film_id = f.film_id)  where film_id = ?";
		jdbcTemplate.update(sqlQuery, filmId);
	}
```
Который убдет автоматом просчитывать рейтинг. Потому что лайки ставяться/удлаяется намного меньше разз, чем фильм получается(вызывается гет), поэтому лучше просчитывать рейтинг при добавлении/удалении, а потом просто получать как поле. 
Чем высчитывать его при каждом получении

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/MpaRepository.java
> +    public Mpa getMpaById(Long id) {
Два одинаковых метода

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/MpaRepository.java
> +
Тут должны быть методы толлько get и getAll
Остальных быть не должно, ведь эти данные неизменяеми и они заводяться на моент старта приложения

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +public class BaseRepository<T> {
В конечном счете у большинства данных базовые методы работают с доп логикой, поэтому сомнительно необходимость этого класса. 
А вот интерфйесы для каждой репозитории сделать стоитло. И работать через интерфйесы

2024-11-14 21:28 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +
Стоит сделать отдельный репозитороий для работы с друзьми

2024-11-15 00:24 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Найдены фильмы: {}", filmRepository.findAll());
Исправил

2024-11-15 00:34 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Получен запрос на получение всех фильмов");
Исправил

2024-11-15 00:47 UTC, Cakypa217 commented on src/main/resources/data.sql
> +
Исправил

2024-11-15 01:03 UTC, Cakypa217 commented on src/main/resources/schema.sql
> +);
Исправил

2024-11-15 01:04 UTC, Cakypa217 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_mpa (
Исправил

2024-11-15 01:38 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        return jdbc.query(FIND_ALL_FILMS, mapper);
Исправил, написал немного по другому, надеюсь не хуже

2024-11-15 01:43 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        List<Genre> genres = genreRepository.getGenresForFilm(filmId);
Исправил

2024-11-15 01:43 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Long mpaId = mpaRepository.getMpaForFilm(filmId);
Исправил

2024-11-15 01:52 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotBlank(message = "Название фильма не может быть пустым")
Исправил

2024-11-15 02:21 UTC, Cakypa217 commented on src/main/resources/schema.sql
> +);
Исправил

2024-11-15 06:14 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmDto updateFilm(NewFilmRequest newFilmRequest) {
Исправил

2024-11-15 06:33 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +
Исправил

2024-11-15 06:37 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +
Исправил

2024-11-15 06:58 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/MpaRepository.java
> +
Исправил

2024-11-15 06:58 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/MpaRepository.java
> +    public Mpa getMpaById(Long id) {
Исправил

2024-11-15 07:44 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/BaseRepository.java
> +public class BaseRepository<T> {
Я попробовал переписать , но тогда очень много тестов не проходит кот в пасмане

2024-11-16 08:02 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/FilmRepository.java
> +        return jdbc.query(FIND_ALL_FILMS, mapper);
Все связанные поля которые можно достать с помощью sql надо делать с помощью запроса. 
Потому что они достаються 1 запросом. И не нужно делать дополнительнрые.

2024-11-16 08:09 UTC, YazykovMikhail requested changes

2024-11-16 08:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +    public List<User> findAll() {
public List<Film> getAll() {
		return jdbcTemplate.query("select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID", DbFilmStorage::makeFilm);
	}
С учетом того что метод makeFilm выглдяит так:
```
static Film makeFilm(ResultSet rs, int rowNum) throws SQLException {
		return new Film(
				rs.getLong("film_id"),
				rs.getString("FILMS.name"),
				rs.getString("description"),
				toLocalDate(rs.getDate("release_date")),
				rs.getLong("duration"),
				rs.getLong("rate"),
				new Mpa(rs.getLong("MPA.mpa_id"), rs.getString("MPA.name")));
	}	
```

2024-11-16 08:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +    public Optional<User> findById(long id) {
Аналогично:
```
	@Override
	public Film get(long id) {
		final String sqlQuery = "select * from FILMS f, MPA m where f.MPA_ID = m.MPA_ID AND FILM_ID = ?";
		final List<Film> films = jdbcTemplate.query(sqlQuery, DbFilmStorage::makeFilm, id);
		if (films.size() != 1) {
			throw new DataNotFoundException("film id=" + id);
		}
		return films.get(0);
	}
```
Можно возвращать Optional

2024-11-16 08:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.forEach(film -> {
Это главная возможность sql что можно вытащить все связанные данные с помощью запроса и это нужно делать. 
Тут ты сейчас делаешь лишний запрос, хотя он не нужен, ведь данные при связи один ко многим можно легко вытащить спомощью запроса, написал в репозитории. 
Тут стоит убрать.

2024-11-16 08:09 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Mpa mpa = mpaRepository.getMpaById(film.getMpa().getId(),
Аналогично нужно реализовыватсья через sql запрос где данные будут возвращаться сразу когда идет поик по фильму

2024-11-16 15:39 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +    public List<User> findAll() {
Исправил

2024-11-16 15:51 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/dal/UserRepository.java
> +    public Optional<User> findById(long id) {
Исправил

2024-11-16 15:54 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        films.forEach(film -> {
Исправил

2024-11-16 15:54 UTC, Cakypa217 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Mpa mpa = mpaRepository.getMpaById(film.getMpa().getId(),
Исправил

2024-11-16 21:57 UTC, YazykovMikhail approved these changes

2024-11-19 16:14 UTC, merged